/**
 * Events data - Auto-generated by update_dtxent workflow
 * Last updated: 2026-04-19 14:33:50
 * Sources: paynearena.com, tixplug.com, zaeee.saffire.com
 */
export const LOCAL_EVENTS = [
    {
        "artistName": "Highly Motavated 420 Comedy Special",
        "eventName": "",
        "eventDate": "2026-04-20T20:00:00",
        "venueName": "Citrus Live",
        "venueCity": "Edinburg",
        "venueState": "TX",
        "imageName": "highly-motivated-420-comedy-special.jpg",
        "imageUrl": "",
        "ticketUrl": "https://tixplug.com/shop/highly-motivated-420-comedy-special/",
        "isPublished": true,
        "schedule": [
            {
                "time": "7:00 PM",
                "description": "Doors Open"
            }
        ],
        "source": "manual"
    },
    {
        "artistName": "Highly Motavated 420 Comedy Special ft Raymond Orta and Friends",
        "eventName": "",
        "eventDate": "2026-04-20T20:00:00",
        "venueName": "Citrus Live",
        "venueCity": "Edinburg",
        "venueState": "TX",
        "imageName": "highly-motivated-420-comedy-special.jpg",
        "imageUrl": "https://tixplug.com/wp-content/uploads/2026/02/1000271766-768x960.jpg",
        "ticketUrl": "https://tixplug.com/shop/highly-motivated-420-comedy-special/",
        "isPublished": true,
        "source": "tixplug",
        "schedule": [
            {
                "time": "7:00 PM",
                "description": "Doors Open"
            }
        ]
    },
    {
        "artistName": "Pop Punk Party Night",
        "eventName": "Anthem 182 (A Tribute to Blink-182)",
        "eventDate": "2026-04-25T20:00:00",
        "venueName": "Citrus Live",
        "venueCity": "Edinburg",
        "venueState": "TX",
        "imageName": "pop-punk-party-night-anthem-182-a-tribute-to-blink-182.jpg",
        "imageUrl": "https://tixplug.com/wp-content/uploads/2026/03/pop-punk-show-768x1152.jpg",
        "ticketUrl": "https://tixplug.com/shop/pop-punk-party-night-anthem-182-a-tribute-to-blink-182/",
        "isPublished": true,
        "schedule": [
            {
                "time": "7:30 PM",
                "description": "Doors Open"
            }
        ],
        "source": "manual"
    },
    {
        "artistName": "Emerson, Lake & Palmer",
        "eventName": "The United Tour",
        "eventDate": "2026-05-01T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-emerson-lake-palmer.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1766465329196-DBEM1LA0KND1P1TN7IDU/Emerson+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/an-evening-with-emerson-lake-palmer-hidalgo-texas-05-01-2026/event/3A006364BE3AA8B1",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "South Side Texas Tour",
        "eventName": "Uno G Live",
        "eventDate": "2026-05-08T20:00:00",
        "venueName": "",
        "venueCity": "",
        "venueState": "TX",
        "imageName": "south-side-texas-tour-uno-g-live.jpg",
        "imageUrl": "https://tixplug.com/wp-content/uploads/2026/04/1000313583-768x1187.jpg",
        "ticketUrl": "https://tixplug.com/shop/south-side-texas-tour-uno-g-live/",
        "isPublished": true,
        "source": "tixplug",
        "schedule": [
            {
                "time": "7:00 PM",
                "description": "Doors Open"
            }
        ],
        "dates": [
            {
                "eventDate": "2026-05-08T20:00:00",
                "ticketUrl": "https://tixplug.com/shop/south-side-texas-tour-uno-g-live/"
            },
            {
                "eventDate": "2026-05-09T20:00:00",
                "ticketUrl": "https://tixplug.com/shop/south-side-texas-tour-uno-g-live-corpus-christi/"
            }
        ]
    },
    {
        "artistName": "City of Alamo Watermelon Fest '26",
        "eventName": "",
        "eventDate": "2026-05-09T20:00:00",
        "venueName": "Alamo Sports Complex",
        "venueCity": "Alamo",
        "venueState": "TX",
        "imageName": "city-of-alamo-watermelon-fest-26.jpg",
        "imageUrl": "",
        "ticketUrl": "https://tixplug.com/shop/city-of-alamo-watermelon-fest-26/",
        "isPublished": true,
        "source": "manual"
    },
    {
        "artistName": "Alejandro Sanz",
        "eventName": "Y Ahora Que Gira",
        "eventDate": "2026-05-09T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-alejandro-sanz.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1761749294639-EUSVBJ2GF58GH2AFO6HC/Alejandro+Sanz+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/alejandro-sanz-y-ahora-que-gira-hidalgo-texas-05-09-2026/event/3A006355DAD69751",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Lost in Hollywood (SOD Tribute) & Testify (RAM Tribute)",
        "eventName": "Citrus Live",
        "eventDate": "2026-05-15T20:00:00",
        "venueName": "Citrus Live",
        "venueCity": "Edinburg",
        "venueState": "TX",
        "imageName": "lost-in-hollywood-testify.png",
        "imageUrl": "",
        "ticketUrl": "https://tixplug.com/shop/lost-in-hollywood-testify/",
        "isPublished": true,
        "schedule": [
            {
                "time": "7:00 PM",
                "description": "Doors Open"
            }
        ],
        "source": "manual"
    },
    {
        "artistName": "Carin León",
        "eventName": "De Sonora Para El Mundo Tour",
        "eventDate": "2026-05-20T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-carin-le-n.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1770340291383-GZQL25PL8JO6PP1B8UZ1/SOCIALS-LEGENDARY-Carin.jpg",
        "ticketUrl": "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-20-2026/event/3A0064309908954C",
        "isPublished": true,
        "source": "paynearena",
        "dates": [
            {
                "eventDate": "2026-05-20T20:00:00",
                "ticketUrl": "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-20-2026/event/3A0064309908954C"
            },
            {
                "eventDate": "2026-05-21T20:00:00",
                "ticketUrl": "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-21-2026/event/3A0064309910955E"
            }
        ]
    },
    {
        "artistName": "Puppy Pals Live",
        "eventName": "Live Show",
        "eventDate": "2026-05-28T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-puppy-pals-live.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1771614548955-C2ZP2KYZOKJITS1VOQVD/daac1bda-2ce5-49e2-ac0c-f909d6dc4343.jpg",
        "ticketUrl": "https://www.ticketmaster.com/puppy-pals-live-hidalgo-texas-05-28-2026/event/3A00644BF7033190",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "NB Ridaz",
        "eventName": "Runaway Throwback Night (Citrus Live) May 29th, 2026",
        "eventDate": "2026-05-29T20:00:00",
        "venueName": "Citrus Live",
        "venueCity": "Edinburg",
        "venueState": "TX",
        "imageName": "nb-ridaz-runaway-throwback-night.jpg",
        "imageUrl": "https://tixplug.com/wp-content/uploads/2026/02/1000287239-768x960.jpg",
        "ticketUrl": "https://tixplug.com/shop/nb-ridaz-runaway-throwback-night/",
        "isPublished": true,
        "schedule": [
            {
                "time": "7:00 PM",
                "description": "Doors Open"
            }
        ],
        "source": "manual"
    },
    {
        "artistName": "Grupo Bryndis, Industria Del Amor & Guardianes",
        "eventName": "Romanticos Tour",
        "eventDate": "2026-05-29T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-grupo-bryndis-industria-del-amor-guardianes.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1768491448319-DPWWPLZUFAXF8VJM2OOB/ROMANTICOS+TOUR+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/grupo-bryndis-industria-del-amor-guardianes-hidalgo-texas-05-29-2026/event/3A00638999886744",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Braxton Keith",
        "eventName": "Live at Payne Arena",
        "eventDate": "2026-06-12T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-braxton-keith.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1771614565625-VYQMU2HAAM3P1FG3UUDF/Braxton+Keith+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/braxton-keith-hidalgo-texas-06-12-2026/event/3A006451C60E4991",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Seltzer Island",
        "eventName": "",
        "eventDate": "2026-06-20T20:00:00",
        "venueName": "Cameron County Amphitheater",
        "venueCity": "South Padre Island",
        "venueState": "TX",
        "imageName": "seltzer-island.jpg",
        "imageUrl": "",
        "ticketUrl": "https://tixplug.com/shop/seltzer-island/",
        "isPublished": true,
        "schedule": [
            {
                "time": "3:00 PM",
                "description": "Doors Open"
            }
        ],
        "source": "manual"
    },
    {
        "artistName": "Seltzer Island Fest (South Padre Island)",
        "eventName": "",
        "eventDate": "2026-06-20T20:00:00",
        "venueName": "Cameron County Amphitheater",
        "venueCity": "",
        "venueState": "TX",
        "imageName": "seltzer-island.jpg",
        "imageUrl": "https://tixplug.com/wp-content/uploads/2026/01/IMG-20260324-WA0060-768x960.jpg",
        "ticketUrl": "https://tixplug.com/shop/seltzer-island/",
        "isPublished": true,
        "source": "tixplug",
        "schedule": [
            {
                "time": "3:00 PM",
                "description": "Doors Open"
            }
        ]
    },
    {
        "artistName": "90S Banda Tour",
        "eventName": "Live at Payne Arena",
        "eventDate": "2026-06-27T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-90s-banda-tour.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1776385340607-HXJ1EYFQ8DYBHGCR3612/90%27s+Banda+Tour+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/90s-banda-tour-hidalgo-texas-06-27-2026/event/3A00647B9F9F9E08",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Marisela Eterna Tour 2026",
        "eventName": "Live at Payne Arena",
        "eventDate": "2026-10-02T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-marisela-eterna-tour-2026.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1774376512288-YIFYTHG5YIZJJ4AP6IKA/Marisela+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/marisela-eterna-tour-2026-hidalgo-texas-10-02-2026/event/3A006471C948CB3E",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Tatiana Los Chicharrines Tativerso Chicharrin",
        "eventName": "Live at Payne Arena",
        "eventDate": "2026-10-10T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-tatiana-los-chicharrines-tativerso-chicharrin.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1776386082196-2G37HSNVHHC5LYXK3MC2/Tatiana+%26+Los+Chicharrines+-+Tativerso+Chicharrin+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/tatiana-los-chicharrines-tativerso-chicharrin-hidalgo-texas-10-10-2026/event/3A00648AB859C90C",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Mon Laferte Femme Fatale Tour",
        "eventName": "Live at Payne Arena",
        "eventDate": "2026-10-17T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-mon-laferte-femme-fatale-tour.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1774376147279-TZSUIX4FVFK7H1EC81AP/Mon+Laferte+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/mon-laferte-femme-fatale-tour-hidalgo-texas-10-17-2026/event/3A00646BDB3AFD98",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Intocable Cultura Tour 2026",
        "eventName": "Live at Payne Arena",
        "eventDate": "2026-11-28T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-intocable-cultura-tour-2026.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1776386355133-LTPBGNCZLBL0LWFND6PN/Intocable+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/intocable-cultura-tour-2026-hidalgo-texas-11-28-2026/event/3A00648CA1E365C8",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Blue October Foiled 20Th Anniversary World",
        "eventName": "Live at Payne Arena",
        "eventDate": "2026-12-13T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-blue-october-foiled-20th-anniversary-world.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1774376792791-RL7ORS7U816FANI9UAGH/Blue+October+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/blue-october-foiled-20th-anniversary-world-hidalgo-texas-12-13-2026/event/3A0064778B494B44",
        "isPublished": true,
        "source": "paynearena"
    },
    {
        "artistName": "Cristian Castro Nada Solo Exitos Tour",
        "eventName": "Live at Payne Arena",
        "eventDate": "2027-02-27T20:00:00",
        "venueName": "Payne Arena",
        "venueCity": "Hidalgo",
        "venueState": "TX",
        "imageName": "payne-cristian-castro-nada-solo-exitos-tour.jpg",
        "imageUrl": "https://images.squarespace-cdn.com/content/v1/5b983da550a54f375e729aa3/1772168986785-1514GYBN7KONKMPRXN4V/Cristian+Castro+WEBSITE.jpg",
        "ticketUrl": "https://www.ticketmaster.com/cristian-castro-nada-solo-exitos-tour-hidalgo-texas-02-27-2027/event/3A006453FBA59815",
        "isPublished": true,
        "source": "paynearena"
    }
];

export const LOCAL_CLUBS = [
    {
        id: "club-1",
        name: "Bau Rooftop",
        type: "Rooftop Lounge",
        city: "McAllen",
        instagram: "letsbau",
        description: "21+ rooftop vibes in Downtown McAllen. Friday and Saturday parties with the best DJs in the Valley.",
        features: ["Rooftop", "DJ Sets", "21+"],
        link: "https://instagram.com/letsbau",
        logoFile: "bau_rooftop_logo.png",
        phone: "956-800-8301"
    },
    {
        id: "club-2",
        name: "NOWHERE",
        type: "Cocktail Bar",
        city: "McAllen",
        instagram: "nowherergv",
        description: "Craft cocktails and an electric atmosphere. Open 5 PM to 2 AM — the place you end up when the night gets good.",
        features: ["Craft Cocktails", "Late Night", "Full Menu"],
        link: "https://linktr.ee/NowhereRGV",
        logoFile: "nowhere_logo.jpg",
        phone: "956-899-7777"
    },
    {
        id: "club-3",
        name: "Tabu Bistro Lounge",
        type: "Bistro Lounge",
        city: "McAllen",
        instagram: "tabumcallen",
        description: "Where the after party begins. Premium cocktails, a seductive ambiance, and the energy to match — Thursday through Saturday.",
        features: ["Cocktails", "VIP", "Late Night"],
        link: "https://tabubistrotx.com",
        logoFile: "tabu_bistro_lounge_logo.webp",
        phone: "956.803.6188"
    }
];

export const LOCAL_RESTAURANTS = [
    {
        id: "food-santa-fe",
        name: "Santa Fe Steakhouse & Cantina",
        type: "Intimate Steakhouse",
        city: "McAllen",
        price: "$$$",
        image: "assets/santa_fe.jpg",
        description: "A McAllen original featuring premium high-quality steaks, an extensive wine list, and an enchanting patio getaway.",
        features: ["Premium Steaks", "600+ Wine Selection", "Rooftop Terrace"],
        link: "https://santafemcallen.com/",
        lat: 26.189,
        lng: -98.231
    },
    {
        id: "food-la-doble-m",
        name: "La Doble M",
        type: "Mexican Fine Dining",
        city: "McAllen",
        price: "$$$",
        image: "assets/la_doble_m.jpg",
        description: "Contemporary Mexican cuisine inspired by the flavors of northern Mexico. Flame-grilled 'brasa' specialties in a sophisticated atmosphere.",
        features: ["Grilled Cuisine", "Upscale Atmosphere", "Live Music"],
        link: "https://grupomendezusa.com/home",
        lat: 26.197,
        lng: -98.272
    },
    {
        id: "food-mousai",
        name: "Mousai Mcallen",
        type: "Asian Fusion",
        city: "McAllen",
        price: "$$$",
        image: "assets/mousai.jpg",
        description: "Chic contemporary Asian dining fusing traditional techniques with modern style. Mood-driven energy with hand-crafted sushi.",
        features: ["Hand-crafted Sushi", "Cocktail Bar", "Digital Ambiance"],
        link: "http://mousaimcallen.com/",
        lat: 26.242,
        lng: -98.212
    }
];

export const DINING_RESTAURANTS = [
    {
        id: "dining-la-doble-m",
        name: "La Doble M",
        instagram: "ladoblem_",
        category: "Mexican Fine Dining",
        bio: "Contemporary Mexican cuisine inspired by northern flavors.",
        address: "McAllen, TX",
        website: "https://grupomendezusa.com/home",
        phone: null,
        followers: "5.8K",
        logoFile: "ladoblem.jpeg",
        imageFile: "logos/ladoblem.jpeg",
        featured: true
    },
    {
        id: "dining-santa-fe",
        name: "Santa Fe Steakhouse & Cantina",
        instagram: "santafesteakhouse",
        category: "Steakhouse",
        bio: "McAllen's premier steakhouse — fine wines and live music.",
        address: "704 E Griffin Pkwy, McAllen, TX",
        website: "santafemcallen.com",
        phone: "(956) 630-2331",
        followers: "6.2K",
        logoFile: "../SantaFeSteak.png",
        imageFile: "../SantaFeSteak.png",
        featured: true
    },
    {
        id: "dining-mousai",
        name: "Mousai Mcallen",
        instagram: "mousaimcallen",
        category: "Asian Fusion",
        bio: "Immersive Asian fusion with hand-crafted sushi and curated energy.",
        address: "McAllen, TX",
        website: "www.mousaimcallen.com",
        phone: null,
        followers: "9.8K",
        logoFile: "MousaiMcallen.png",
        imageFile: "logos/MousaiMcallen.png",
        featured: true
    },
    {
        id: "dining-01",
        name: "RU",
        instagram: "ru.mcallen",
        category: "Fine Dining",
        bio: "COCINA SIN LÍMITES — bold, boundary-breaking cuisine.",
        address: "5800 N 10th St Suite 340, McAllen TX",
        website: "www.ru-restaurant.com",
        phone: null,
        followers: "12.2K",
        logoFile: "ru_logo.png",
        featured: false
    },
    {
        id: "dining-02",
        name: "Camaleon by Don Arturo",
        instagram: "camaleontx",
        category: "Seafood",
        bio: "Where the sea changes its skin — fresh seafood and late-night vibes.",
        address: "2901 W Expy 83, McAllen, Texas",
        website: "camaleonmcallen.com/menu",
        phone: "(956) 339-4346",
        followers: "2,447",
        logoFile: "camaleon_by_don_arturo_logo.jpg",
        featured: false
    },
    {
        id: "dining-03",
        name: "Sidebar RGV",
        instagram: "sidebar_rgv",
        category: "Fine Dining",
        bio: "Golden Age dining meets hand-crafted cocktails, fine wines, and jazz.",
        address: null,
        website: "www.sidebar215.com/events",
        phone: null,
        followers: "11.4K",
        logoFile: "sidebar_rgv_logo.png",
        featured: false
    },
    {
        id: "dining-04",
        name: "Winecow Argentina Steak House",
        instagram: "winecow_",
        category: "Steakhouse",
        bio: "Buen bife, buen vino, buena música — Argentine asado done right.",
        address: "4900 W Expressway 83 Ste 380, McAllen, Texas",
        website: "https://www.facebook.com/WinecowARG/",
        phone: "(956) 569-3162",
        followers: "3,419",
        logoFile: "winecow_logo.png",
        featured: false
    },
    {
        id: "dining-05",
        name: "The Patio On Guerra",
        instagram: "patioonguerra",
        category: "Fine Dining",
        bio: "Prime steaks, seafood, wine, and full bar in Historic Downtown McAllen.",
        address: "116 S 17th St, McAllen, Texas",
        website: "www.patioonguerra.com",
        phone: "(956) 661-9100",
        followers: "4,487",
        logoFile: "the_patio_on_guerra_logo.png",
        featured: false
    },
    {
        id: "dining-06",
        name: "SALT — New American Table",
        instagram: "saltnewamericantable",
        category: "Fine Dining",
        bio: "Where global flavors meet local pride. Your seat's waiting.",
        address: "210 N Main St, McAllen, Texas",
        website: "saltnewamericantable.com/home",
        phone: null,
        followers: "8,842",
        logoFile: "salt_new_american_table_logo.png",
        featured: false
    },
    {
        id: "dining-08",
        name: "Ambra",
        instagram: "ambramcallen",
        category: "Fine Dining",
        bio: "Charcoal fire cuisine — redefining the art of grilling. Smart dress code enforced.",
        address: "1200 Auburn Ave Suite 200, McAllen, Texas",
        website: "ambramcallen.com",
        phone: null,
        followers: "17.5K",
        logoFile: "ambra_by_altura_concepts_logo.png",
        imageFile: "ambra_bg.jpg",
        featured: false
    },
    {
        id: "dining-09",
        name: "Palominos McAllen",
        instagram: "palominosmcallen",
        category: "Steakhouse",
        bio: "Grilled masters since 1974 — open every day starting at noon.",
        address: "4117 W Expy 83, McAllen, TX 78501",
        website: "www.restaurantpalominos.com",
        phone: null,
        followers: "12.8K",
        logoFile: "palominos_mcallen_logo.png",
        featured: false
    },
    {
        id: "dining-10",
        name: "Tabu Bistro Lounge",
        instagram: "tabumcallen",
        category: "Cocktail Bar",
        bio: "Bistro lounge with craft cocktails and Sunday brunch in a seductive setting.",
        address: null,
        website: "https://tabubistrotx.com",
        phone: "956.803.6188",
        followers: "18.9K",
        logoFile: "tabu_bistro_lounge_logo.webp",
        imageFile: "tabu_bg.webp",
        featured: false
    },
    {
        id: "dining-12",
        name: "The Loretto at Mission",
        instagram: "thelorettoatmission",
        category: "Unique Experiences",
        bio: "New American dining in the heart of Mission — brunch, dinner, craft cocktails, and live music.",
        address: "1233 East Griffin Parkway, Mission, Texas",
        website: "lorettobistro.com",
        phone: null,
        followers: "17.6K",
        logoFile: "the_loretto_at_mission_logo.png",
        imageFile: "loretto_bg.jpg",
        featured: false
    },
    {
        id: "dining-13",
        name: "Moon Restaurant + Mixology",
        instagram: "moonrestaurantmixology",
        category: "Unique Experiences",
        bio: "Redefining dining in the RGV — global cuisine and craft cocktails.",
        address: "1603 E Griffin Pkwy, Mission, Texas",
        website: "https://moonrestaurantmixology.com",
        phone: "(956) 974-2465",
        followers: "9,002",
        logoFile: "moon_restaurant_logo.jpg",
        featured: false
    },
    {
        id: "dining-14",
        name: "SSTASH",
        instagram: "sstashburger",
        category: "Unique Experiences",
        bio: "Smashburgers made with locally sourced premium Akaushi beef — open until sold out.",
        address: "308 N Shary Rd Suite C, Mission, Texas",
        website: null,
        phone: null,
        followers: "5,744",
        logoFile: "sstash_logo.png",
        featured: false
    },
    {
        id: "dining-15",
        name: "Brunetta",
        instagram: "brunetta_restaurant",
        category: "Brunch & Cafe",
        bio: "Tinto and pasta — Italian-inspired dining in McAllen.",
        address: "3300 W Expressway 83 Suite 160, McAllen, TX",
        website: "brunettatintoandpasta.com/menu",
        phone: "956-540-7144",
        followers: "5,149",
        logoFile: "brunetta_logo.png",
        featured: false
    },
    {
        id: "dining-16",
        name: "RICARDI café",
        instagram: "ricardicafeofficial",
        category: "Brunch & Cafe",
        bio: "STILE DI VITA LATINO — café, food, fashion, and music.",
        address: "1601 E Griffin Pkwy, Mission, Texas",
        website: "ricardicafe0306.s4shops.com",
        phone: null,
        followers: "522",
        logoFile: "ricardi_cafe_logo.png",
        featured: false
    },
    {
        id: "dining-17",
        name: "NOWHERE",
        instagram: "nowherergv",
        category: "Cocktail Bar",
        bio: "Cocktail bar and restaurant — open 5 PM to 2 AM.",
        address: "4037 W Expy 83 Suite 100, McAllen, Texas",
        website: "linktr.ee/NowhereRGV",
        phone: "956-899-7777",
        followers: "1,180",
        logoFile: "nowhere_logo.jpg",
        featured: false
    },
    {
        id: "dining-18",
        name: "Casa de Palmas",
        instagram: "casadepalmashotel",
        category: "Unique Experiences",
        bio: "McAllen's most distinctive hotel — reflecting the history of the Rio Grande Valley.",
        address: null,
        website: "https://www.wyndhamhotels.com/trademark/mcallen-texas/casa-de-palmas-trademark-collection/overview",
        phone: null,
        followers: "2,941",
        logoFile: "casa_de_palmas_logo.png",
        featured: false
    },
    {
        id: "dining-19",
        name: "Casa Madre",
        instagram: "casa_madree",
        category: "Steakhouse",
        bio: "Honest experience — five-star brunch and steakhouse. Home of the Caramelo.",
        address: "2200 S 10th St Suite S05, McAllen, TX 78503",
        website: "https://www.instagram.com/casamadremcallen/",
        phone: null,
        followers: "97.2K",
        logoFile: "casa_madre_logo.png",
        featured: false
    },
    {
        id: "dining-20",
        name: "Casa Jardín",
        instagram: "casajardintx",
        category: "Brunch & Cafe",
        bio: "Coffee, brunch, and bakery — with drive-thru opening at 6:30 AM.",
        address: null,
        website: "casajardintx.com/reserve-a-table",
        phone: null,
        followers: "4,321",
        logoFile: "casa_jardin_logo.png",
        featured: false
    },
    {
        id: "dining-21",
        name: "Rancho El Charco",
        instagram: "rancho.el.charco",
        category: "Unique Experiences",
        bio: "South Texas hidden gem — 150-acre ranch with lodging, safari glamping, and private retreats.",
        address: null,
        website: "ranchoelcharco.com",
        phone: null,
        followers: "6,785",
        logoFile: "rancho_el_charco_logo.png",
        featured: false
    },
    {
        id: "dining-22",
        name: "Bau Rooftop",
        instagram: "letsbau",
        category: "Cocktail Bar",
        bio: "21+ rooftop vibes — Friday and Saturday parties in Downtown McAllen.",
        address: "122 S. 17th St, McAllen, Texas",
        website: null,
        phone: "956-800-8301",
        followers: "6,347",
        logoFile: "bau_rooftop_logo.png",
        featured: false
    }
];

export const LOCAL_HOTELS = [
    {
        id: "hotel-1",
        name: "Embassy Suites Convention Center",
        city: "McAllen",
        stars: 4,
        image: "assets/embassy-mcallen.png",
        description: "Located within walking distance of the McAllen Convention Center district.",
        features: ["Free Breakfast", "Pool", "Suites"],
        link: "https://www.hilton.com",
        lat: 26.195,
        lng: -98.257
    },
    {
        id: "hotel-2",
        name: "Isla Grand Beach Resort",
        city: "South Padre Island",
        stars: 4,
        image: "assets/isla-grand.png",
        description: "A beachfront resort offering a tropical escape with pools and dining.",
        features: ["Beachfront", "Resort Style", "Nightclub on-site"],
        link: "https://islagrand.com",
        lat: 26.090,
        lng: -97.160
    }
];
