/**
 * Events data - Auto-generated by scrape_events workflow
 * Last updated: 2026-02-21 00:27:17
 * Sources: tixplug.com, paynearena.com
 */
export const LOCAL_EVENTS = [
    {
        artistName: "Mötley KRÜE",
        eventName: "A Tribute to Mötley Crue (RAILYARD 83)",
        eventDate: "2026-02-21T20:00:00",
        venueName: "Rail",
        venueCity: "Alamo",
        venueState: "TX",
        imageName: "motley-kue-a-tribute-to-motley-crue.jpg",
        ticketUrl: "https://tixplug.com/shop/motley-kue-a-tribute-to-motley-crue/",
        schedule: [
            { time: "7:00 PM", description: "Doors Open" },
            { time: "9:00 PM", description: "Show Starts" }
        ],
        isPublished: true
    },
    {
        artistName: "Cartel Bo",
        eventName: "Hit for a Bag Tour (Corpus Christi, TX)",
        eventDate: "2026-02-27T20:00:00",
        venueName: "The Nest",
        venueCity: "Corpus Christi",
        venueState: "TX",
        imageName: "cartel-bo-hit-for-a-bag-tour-corpus-christi-tx.jpg",
        ticketUrl: "https://tixplug.com/shop/cartel-bo-hit-for-a-bag-tour-corpus-christi-tx/",
        isPublished: true
    },
    {
        artistName: "Cartel Bo",
        eventName: "Hit for a Bag Tour (McAllen, TX)",
        eventDate: "2026-02-28T20:00:00",
        venueName: "Presi",
        venueCity: "Allen",
        venueState: "TX",
        imageName: "cartel-bo-hit-for-a-bag-tour-mcallen-tx.jpg",
        ticketUrl: "https://tixplug.com/shop/cartel-bo-hit-for-a-bag-tour-mcallen-tx/",
        isPublished: true
    },
    {
        artistName: "Gulf Coast Comedy ft. CHINGO BLING (CORPUS CHRISTI)",
        eventName: "",
        eventDate: "2026-03-07T20:00:00",
        venueName: "The Nest",
        venueCity: "Corpus Christi",
        venueState: "TX",
        imageName: "gulf-coast-comedy.jpg",
        ticketUrl: "https://tixplug.com/shop/gulf-coast-comedy/",
        schedule: [
            { time: "5:30 PM", description: "Doors Open" },
            { time: "6:30 PM", description: "Show Starts" }
        ],
        isPublished: true
    },
    {
        artistName: "Los Angeles Azules",
        eventName: "Cumbia Sin Fronteras US Tour",
        eventDate: "2026-03-07T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-los-angeles-azules.jpg",
        ticketUrl: "https://www.ticketmaster.com/los-angeles-azules-cumbia-sin-fronteras-hidalgo-texas-03-07-2026/event/3A00634E94D967D7",
        isPublished: true
    },
    {
        artistName: "Kodak Black",
        eventName: "Live in Concert",
        eventDate: "2026-03-12T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-kodak-black.jpg",
        ticketUrl: "https://www.ticketmaster.com/kodak-black-hidalgo-texas-03-12-2026/event/3A006443DF90C757",
        isPublished: true
    },
    {
        artistName: "Manuel Turizo",
        eventName: "Borderfest 2026",
        eventDate: "2026-03-13T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-manuel-turizo.jpg",
        ticketUrl: "https://www.ticketmaster.com/hidalgo-borderfest-manuel-turizo-hidalgo-texas-03-13-2026/event/3A006442FF94D936",
        isPublished: true
    },
    {
        artistName: "Citrus Break Comedy Show w/ MIKE Winfield (Citrus LIVE)",
        eventName: "",
        eventDate: "2026-03-21T20:00:00",
        venueName: "Citrus Live",
        venueCity: "Edinburg",
        venueState: "TX",
        imageName: "citrus-break-comedy-show.jpg",
        ticketUrl: "https://tixplug.com/shop/citrus-break-comedy-show/",
        isPublished: true
    },
    {
        artistName: "Panter Belico",
        eventName: "Live in Concert",
        eventDate: "2026-03-21T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-panter-belico.jpg",
        ticketUrl: "https://www.ticketmaster.com/panter-belico-hidalgo-texas-03-21-2026/event/3A006338AC3E4B8B",
        isPublished: true
    },
    {
        artistName: "Reik",
        eventName: "Tour 2026",
        eventDate: "2026-03-28T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-reik.jpg",
        ticketUrl: "https://www.ticketmaster.com/reik-tour-2026-hidalgo-texas-03-28-2026/event/3A006377F8B7D2C4",
        isPublished: true
    },
    {
        artistName: "SOL PADRE (South Padre Island)",
        eventName: "",
        eventDate: "2026-04-03T20:00:00",
        venueName: "Cameron County Amphitheater",
        venueCity: "South Padre Island",
        venueState: "TX",
        imageName: "sol-padre.jpg",
        ticketUrl: "https://tixplug.com/shop/sol-padre/",
        schedule: [
            { time: "7:00 PM", description: "Doors Open" }
        ],
        isPublished: true
    },
    {
        artistName: "Highly Motavated 420 Comedy Special",
        eventName: "",
        eventDate: "2026-04-20T20:00:00",
        venueName: "Citrus Live",
        venueCity: "Edinburg",
        venueState: "TX",
        imageName: "highly-motivated-420-comedy-special.jpg",
        ticketUrl: "https://tixplug.com/shop/highly-motivated-420-comedy-special/",
        schedule: [
            { time: "7:00 PM", description: "Doors Open" }
        ],
        isPublished: true
    },
    {
        artistName: "Snow Tha Product",
        eventName: "BEFORE I CRASHOUT",
        eventDate: "2026-05-01T20:00:00",
        venueName: "HAPO Center",
        venueCity: "Pasco",
        venueState: "WA",
        imageName: "snow-tha-product-before-i-crashout.jpg",
        ticketUrl: "https://tixplug.com/shop/snow-tha-product-before-i-crashout/",
        isPublished: true
    },
    {
        artistName: "Emerson, Lake & Palmer",
        eventName: "The United Tour",
        eventDate: "2026-05-01T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-emerson-lake-palmer.jpg",
        ticketUrl: "https://www.ticketmaster.com/an-evening-with-emerson-lake-palmer-hidalgo-texas-05-01-2026/event/3A006364BE3AA8B1",
        isPublished: true
    },
    {
        artistName: "City of Alamo Watermelon Fest ’26",
        eventName: "",
        eventDate: "2026-05-09T20:00:00",
        venueName: "Alamo Sports Complex",
        venueCity: "Alamo",
        venueState: "TX",
        imageName: "city-of-alamo-watermelon-fest-26.jpg",
        ticketUrl: "https://tixplug.com/shop/city-of-alamo-watermelon-fest-26/",
        isPublished: true
    },
    {
        artistName: "Alejandro Sanz",
        eventName: "Y Ahora Que Gira",
        eventDate: "2026-05-09T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-alejandro-sanz.jpg",
        ticketUrl: "https://www.ticketmaster.com/alejandro-sanz-y-ahora-que-gira-hidalgo-texas-05-09-2026/event/3A006355DAD69751",
        isPublished: true
    },
    {
        artistName: "Tacos, Tequilas & Chelas",
        eventName: "",
        eventDate: "2026-05-16T20:00:00",
        venueName: "Benton County Fairgrounds",
        venueCity: "",
        venueState: "TX",
        imageName: "tacos-tequilas-chelas.jpg",
        ticketUrl: "https://tixplug.com/shop/tacos-tequilas-chelas/",
        isPublished: true
    },
    {
        artistName: "Carin León",
        eventName: "De Sonora Para El Mundo Tour",
        eventDate: "2026-05-20T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-carin-le-n.jpg",
        ticketUrl: "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-20-2026/event/3A0064309908954C",
        dates: [
            { eventDate: "2026-05-20T20:00:00", ticketUrl: "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-20-2026/event/3A0064309908954C" },
            { eventDate: "2026-05-21T20:00:00", ticketUrl: "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-21-2026/event/3A0064309910955E" }
        ],
        isPublished: true
    },
    {
        artistName: "Puppy Pals Live",
        eventName: "Live Show",
        eventDate: "2026-05-28T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-puppy-pals-live.jpg",
        ticketUrl: "https://www.ticketmaster.com/puppy-pals-live-hidalgo-texas-05-28-2026/event/3A00644BF7033190",
        isPublished: true
    },
    {
        artistName: "Grupo Bryndis, Industria Del Amor & Guardianes",
        eventName: "Romanticos Tour",
        eventDate: "2026-05-29T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-grupo-bryndis-industria-del-amor-guardianes.jpg",
        ticketUrl: "https://www.ticketmaster.com/grupo-bryndis-industria-del-amor-guardianes-hidalgo-texas-05-29-2026/event/3A00638999886744",
        isPublished: true
    },
    {
        artistName: "Braxton Keith",
        eventName: "Live at Payne Arena",
        eventDate: "2026-06-12T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-braxton-keith.jpg",
        ticketUrl: "https://www.ticketmaster.com/braxton-keith-hidalgo-texas-06-12-2026/event/3A006451C60E4991",
        isPublished: true
    },
    {
        artistName: "Seltzer Island",
        eventName: "",
        eventDate: "2026-06-20T20:00:00",
        venueName: "Cameron County Amphitheater",
        venueCity: "",
        venueState: "TX",
        imageName: "seltzer-island.jpg",
        ticketUrl: "https://tixplug.com/shop/seltzer-island/",
        schedule: [
            { time: "3:00 PM", description: "Doors Open" }
        ],
        isPublished: true
    }
];

export const LOCAL_CLUBS = [
    {
        id: "club-1",
        name: "Bau Rooftop",
        type: "Rooftop Lounge",
        city: "McAllen",
        instagram: "letsbau",
        description: "21+ rooftop vibes in Downtown McAllen. Friday and Saturday parties with the best DJs in the Valley.",
        features: ["Rooftop", "DJ Sets", "21+"],
        link: "https://instagram.com/letsbau",
        logoFile: "bau_rooftop_logo.png",
        phone: "956-800-8301"
    },
    {
        id: "club-2",
        name: "NOWHERE",
        type: "Cocktail Bar",
        city: "McAllen",
        instagram: "nowherergv",
        description: "Craft cocktails and an electric atmosphere. Open 5 PM to 2 AM — the place you end up when the night gets good.",
        features: ["Craft Cocktails", "Late Night", "Full Menu"],
        link: "https://linktr.ee/NowhereRGV",
        logoFile: "nowhere_logo.jpg",
        phone: "956-899-7777"
    },
    {
        id: "club-3",
        name: "Tabu Bistro Lounge",
        type: "Bistro Lounge",
        city: "McAllen",
        instagram: "tabumcallen",
        description: "Where the after party begins. Premium cocktails, a seductive ambiance, and the energy to match — Thursday through Saturday.",
        features: ["Cocktails", "VIP", "Late Night"],
        link: "https://tabubistrotx.com",
        logoFile: "tabu_bistro_lounge_logo.webp",
        phone: "956.803.6188"
    }
];

export const LOCAL_RESTAURANTS = [
    {
        id: "food-santa-fe",
        name: "Santa Fe Steakhouse & Cantina",
        type: "Intimate Steakhouse",
        city: "McAllen",
        price: "$$$",
        image: "assets/santa_fe.jpg",
        description: "A McAllen original featuring premium high-quality steaks, an extensive wine list, and an enchanting patio getaway.",
        features: ["Premium Steaks", "600+ Wine Selection", "Rooftop Terrace"],
        link: "https://santafemcallen.com/",
        lat: 26.189,
        lng: -98.231
    },
    {
        id: "food-la-doble-m",
        name: "La Doble M",
        type: "Mexican Fine Dining",
        city: "McAllen",
        price: "$$$",
        image: "assets/la_doble_m.jpg",
        description: "Contemporary Mexican cuisine inspired by the flavors of northern Mexico. Flame-grilled 'brasa' specialties in a sophisticated atmosphere.",
        features: ["Grilled Cuisine", "Upscale Atmosphere", "Live Music"],
        link: "https://grupomendezusa.com/home",
        lat: 26.197,
        lng: -98.272
    },
    {
        id: "food-mousai",
        name: "Mousai Mcallen",
        type: "Asian Fusion",
        city: "McAllen",
        price: "$$$",
        image: "assets/mousai.jpg",
        description: "Chic contemporary Asian dining fusing traditional techniques with modern style. Mood-driven energy with hand-crafted sushi.",
        features: ["Hand-crafted Sushi", "Cocktail Bar", "Digital Ambiance"],
        link: "http://mousaimcallen.com/",
        lat: 26.242,
        lng: -98.212
    }
];

export const DINING_RESTAURANTS = [
    {
        id: "dining-la-doble-m",
        name: "La Doble M",
        instagram: "ladoblem_",
        category: "Mexican Fine Dining",
        bio: "Contemporary Mexican cuisine inspired by northern flavors. Flame-grilled 'brasa' specialties in an upscale setting.",
        address: "McAllen, TX",
        website: "https://grupomendezusa.com/home",
        phone: null,
        followers: "5.8K",
        logoFile: "ladoblem.jpeg",
        imageFile: null,
        featured: true
    },
    {
        id: "dining-santa-fe",
        name: "Santa Fe Steakhouse & Cantina",
        instagram: "santafesteakhouse",
        category: "Steakhouse",
        bio: "McAllen's premier steakhouse featuring award-winning steaks, 600+ wine selection, and live music.",
        address: "704 E Griffin Pkwy, McAllen, TX",
        website: "santafemcallen.com",
        phone: "(956) 630-2331",
        followers: "6.2K",
        logoFile: "SantaFeSteak.png",
        imageFile: null,
        featured: true
    },
    {
        id: "dining-mousai",
        name: "Mousai Mcallen",
        instagram: "mousaimcallen",
        category: "Asian Fusion",
        bio: "Immersive contemporary Asian dining experience with hand-crafted sushi and curated energy.",
        address: "McAllen, TX",
        website: "www.mousaimcallen.com",
        phone: null,
        followers: "9.8K",
        logoFile: "MousaiMcallen.png",
        imageFile: "mousai.jpg",
        featured: true
    },
    {
        id: "dining-01",
        name: "RU",
        instagram: "ru.mcallen",
        category: "Fine Dining",
        bio: "COCINA SIN LÍMITES — bold, boundary-breaking cuisine.",
        address: "5800 N 10th St Suite 340, McAllen TX",
        website: "www.ru-restaurant.com",
        phone: null,
        followers: "12.2K",
        logoFile: "ru_logo.png",
        featured: false
    },
    {
        id: "dining-02",
        name: "Camaleon by Don Arturo",
        instagram: "camaleontx",
        category: "Seafood",
        bio: "Where the sea changes its skin — fresh seafood and late-night vibes.",
        address: "2901 W Expy 83, McAllen, Texas",
        website: "camaleonmcallen.com/menu",
        phone: "(956) 339-4346",
        followers: "2,447",
        logoFile: "camaleon_by_don_arturo_logo.jpg",
        featured: false
    },
    {
        id: "dining-03",
        name: "Sidebar RGV",
        instagram: "sidebar_rgv",
        category: "Fine Dining",
        bio: "Golden Age dining meets hand-crafted cocktails, fine wines, and jazz.",
        address: null,
        website: "www.sidebar215.com/events",
        phone: null,
        followers: "11.4K",
        logoFile: "sidebar_rgv_logo.png",
        featured: false
    },
    {
        id: "dining-04",
        name: "Winecow Argentina Steak House",
        instagram: "winecow_",
        category: "Steakhouse",
        bio: "Buen bife, buen vino, buena música — Argentine asado done right.",
        address: "4900 W Expressway 83 Ste 380, McAllen, Texas",
        website: "https://www.facebook.com/WinecowARG/",
        phone: "(956) 569-3162",
        followers: "3,419",
        logoFile: "winecow_logo.png",
        featured: false
    },
    {
        id: "dining-05",
        name: "The Patio On Guerra",
        instagram: "patioonguerra",
        category: "Fine Dining",
        bio: "Prime steaks, seafood, wine, and full bar in Historic Downtown McAllen.",
        address: "116 S 17th St, McAllen, Texas",
        website: "www.patioonguerra.com",
        phone: "(956) 661-9100",
        followers: "4,487",
        logoFile: "the_patio_on_guerra_logo.png",
        featured: false
    },
    {
        id: "dining-06",
        name: "SALT — New American Table",
        instagram: "saltnewamericantable",
        category: "Fine Dining",
        bio: "Where global flavors meet local pride. Your seat's waiting.",
        address: "210 N Main St, McAllen, Texas",
        website: "saltnewamericantable.com/home",
        phone: null,
        followers: "8,842",
        logoFile: "salt_new_american_table_logo.png",
        featured: false
    },
    {
        id: "dining-08",
        name: "Ambra",
        instagram: "ambramcallen",
        category: "Fine Dining",
        bio: "Charcoal fire cuisine — redefining the art of grilling. Smart dress code enforced.",
        address: "1200 Auburn Ave Suite 200, McAllen, Texas",
        website: "ambramcallen.com",
        phone: null,
        followers: "17.5K",
        logoFile: "ambra_by_altura_concepts_logo.png",
        imageFile: "ambra_bg.jpg",
        featured: false
    },
    {
        id: "dining-09",
        name: "Palominos McAllen",
        instagram: "palominosmcallen",
        category: "Steakhouse",
        bio: "Grilled masters since 1974 — open every day starting at noon.",
        address: "4117 W Expy 83, McAllen, TX 78501",
        website: "www.restaurantpalominos.com",
        phone: null,
        followers: "12.8K",
        logoFile: "palominos_mcallen_logo.png",
        featured: false
    },
    {
        id: "dining-10",
        name: "Tabu Bistro Lounge",
        instagram: "tabumcallen",
        category: "Cocktail Bar",
        bio: "Bistro lounge with craft cocktails and Sunday brunch in a seductive setting.",
        address: null,
        website: "https://tabubistrotx.com",
        phone: "956.803.6188",
        followers: "18.9K",
        logoFile: "tabu_bistro_lounge_logo.webp",
        imageFile: "tabu_bg.webp",
        featured: false
    },
    {
        id: "dining-12",
        name: "The Loretto at Mission",
        instagram: "thelorettoatmission",
        category: "Unique Experiences",
        bio: "New American dining in the heart of Mission — brunch, dinner, craft cocktails, and live music.",
        address: "1233 East Griffin Parkway, Mission, Texas",
        website: "lorettobistro.com",
        phone: null,
        followers: "17.6K",
        logoFile: "the_loretto_at_mission_logo.png",
        imageFile: "loretto_bg.jpg",
        featured: false
    },
    {
        id: "dining-13",
        name: "Moon Restaurant + Mixology",
        instagram: "moonrestaurantmixology",
        category: "Unique Experiences",
        bio: "Redefining dining in the RGV — global cuisine and craft cocktails.",
        address: "1603 E Griffin Pkwy, Mission, Texas",
        website: "https://moonrestaurantmixology.com",
        phone: "(956) 974-2465",
        followers: "9,002",
        logoFile: "moon_restaurant_logo.jpg",
        featured: false
    },
    {
        id: "dining-14",
        name: "SSTASH",
        instagram: "sstashburger",
        category: "Unique Experiences",
        bio: "Smashburgers made with locally sourced premium Akaushi beef — open until sold out.",
        address: "308 N Shary Rd Suite C, Mission, Texas",
        website: null,
        phone: null,
        followers: "5,744",
        logoFile: "sstash_logo.png",
        featured: false
    },
    {
        id: "dining-15",
        name: "Brunetta",
        instagram: "brunetta_restaurant",
        category: "Brunch & Cafe",
        bio: "Tinto and pasta — Italian-inspired dining in McAllen.",
        address: "3300 W Expressway 83 Suite 160, McAllen, TX",
        website: "brunettatintoandpasta.com/menu",
        phone: "956-540-7144",
        followers: "5,149",
        logoFile: "brunetta_logo.png",
        featured: false
    },
    {
        id: "dining-16",
        name: "RICARDI café",
        instagram: "ricardicafeofficial",
        category: "Brunch & Cafe",
        bio: "STILE DI VITA LATINO — café, food, fashion, and music.",
        address: "1601 E Griffin Pkwy, Mission, Texas",
        website: "ricardicafe0306.s4shops.com",
        phone: null,
        followers: "522",
        logoFile: "ricardi_cafe_logo.png",
        featured: false
    },
    {
        id: "dining-17",
        name: "NOWHERE",
        instagram: "nowherergv",
        category: "Cocktail Bar",
        bio: "Cocktail bar and restaurant — open 5 PM to 2 AM.",
        address: "4037 W Expy 83 Suite 100, McAllen, Texas",
        website: "linktr.ee/NowhereRGV",
        phone: "956-899-7777",
        followers: "1,180",
        logoFile: "nowhere_logo.jpg",
        featured: false
    },
    {
        id: "dining-18",
        name: "Casa de Palmas",
        instagram: "casadepalmashotel",
        category: "Unique Experiences",
        bio: "McAllen's most distinctive hotel — reflecting the history of the Rio Grande Valley.",
        address: null,
        website: "https://www.wyndhamhotels.com/trademark/mcallen-texas/casa-de-palmas-trademark-collection/overview",
        phone: null,
        followers: "2,941",
        logoFile: "casa_de_palmas_logo.png",
        featured: false
    },
    {
        id: "dining-19",
        name: "Casa Madre",
        instagram: "casa_madree",
        category: "Steakhouse",
        bio: "Honest experience — five-star brunch and steakhouse. Home of the Caramelo.",
        address: "2200 S 10th St Suite S05, McAllen, TX 78503",
        website: "https://www.instagram.com/casamadremcallen/",
        phone: null,
        followers: "97.2K",
        logoFile: "casa_madre_logo.png",
        featured: false
    },
    {
        id: "dining-20",
        name: "Casa Jardín",
        instagram: "casajardintx",
        category: "Brunch & Cafe",
        bio: "Coffee, brunch, and bakery — with drive-thru opening at 6:30 AM.",
        address: null,
        website: "casajardintx.com/reserve-a-table",
        phone: null,
        followers: "4,321",
        logoFile: "casa_jardin_logo.png",
        featured: false
    },
    {
        id: "dining-21",
        name: "Rancho El Charco",
        instagram: "rancho.el.charco",
        category: "Unique Experiences",
        bio: "South Texas hidden gem — 150-acre ranch with lodging, safari glamping, and private retreats.",
        address: null,
        website: "ranchoelcharco.com",
        phone: null,
        followers: "6,785",
        logoFile: "rancho_el_charco_logo.png",
        featured: false
    },
    {
        id: "dining-22",
        name: "Bau Rooftop",
        instagram: "letsbau",
        category: "Cocktail Bar",
        bio: "21+ rooftop vibes — Friday and Saturday parties in Downtown McAllen.",
        address: "122 S. 17th St, McAllen, Texas",
        website: null,
        phone: "956-800-8301",
        followers: "6,347",
        logoFile: "bau_rooftop_logo.png",
        featured: false
    }
];

export const LOCAL_HOTELS = [
    {
        id: "hotel-1",
        name: "Embassy Suites Convention Center",
        city: "McAllen",
        stars: 4,
        image: "assets/embassy-mcallen.png",
        description: "Located within walking distance of the McAllen Convention Center district.",
        features: ["Free Breakfast", "Pool", "Suites"],
        link: "https://www.hilton.com",
        lat: 26.195,
        lng: -98.257
    },
    {
        id: "hotel-2",
        name: "Isla Grand Beach Resort",
        city: "South Padre Island",
        stars: 4,
        image: "assets/isla-grand.png",
        description: "A beachfront resort offering a tropical escape with pools and dining.",
        features: ["Beachfront", "Resort Style", "Nightclub on-site"],
        link: "https://islagrand.com",
        lat: 26.090,
        lng: -97.160
    }
];
