/**
 * Events data - Auto-generated by scrape_events workflow
 * Last updated: 2026-02-16 09:54:54
 * Sources: tixplug.com, paynearena.com
 */
export const LOCAL_EVENTS = [
    {
        artistName: "Mötley KRÜE",
        eventName: "A Tribute to Mötley Crue (RAILYARD 83)",
        eventDate: "2026-02-21T20:00:00",
        venueName: "Rail",
        venueCity: "Alamo",
        venueState: "TX",
        imageName: "motley-kue-a-tribute-to-motley-crue.jpg",
        ticketUrl: "https://tixplug.com/shop/motley-kue-a-tribute-to-motley-crue/",
        schedule: [
            { time: "7:00 PM", description: "Doors Open" },
            { time: "9:00 PM", description: "Show Starts" }
        ],
        isPublished: true
    },
    {
        artistName: "Gulf Coast Comedy",
        eventName: "",
        eventDate: "2026-03-07T20:00:00",
        venueName: "The Nest",
        venueCity: "Corpus Christi",
        venueState: "TX",
        imageName: "gulf-coast-comedy.jpg",
        ticketUrl: "https://tixplug.com/shop/gulf-coast-comedy/",
        schedule: [
            { time: "5:30 PM", description: "Doors Open" },
            { time: "6:30 PM", description: "Show Starts" }
        ],
        isPublished: true
    },
    {
        artistName: "Los Angeles Azules",
        eventName: "Cumbia Sin Fronteras US Tour",
        eventDate: "2026-03-07T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-los-angeles-azules.jpg",
        ticketUrl: "https://www.ticketmaster.com/los-angeles-azules-cumbia-sin-fronteras-hidalgo-texas-03-07-2026/event/3A00634E94D967D7",
        isPublished: true
    },
    {
        artistName: "Kodak Black",
        eventName: "Live in Concert",
        eventDate: "2026-03-12T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-kodak-black.jpg",
        ticketUrl: "https://www.ticketmaster.com/kodak-black-hidalgo-texas-03-12-2026/event/3A006443DF90C757",
        isPublished: true
    },
    {
        artistName: "Manuel Turizo",
        eventName: "Borderfest 2026",
        eventDate: "2026-03-13T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-manuel-turizo.jpg",
        ticketUrl: "https://www.ticketmaster.com/hidalgo-borderfest-manuel-turizo-hidalgo-texas-03-13-2026/event/3A006442FF94D936",
        isPublished: true
    },
    {
        artistName: "Citrus Break Comedy Show w/ MIKE Winfield (Citrus LIVE)",
        eventName: "",
        eventDate: "2026-03-21T20:00:00",
        venueName: "Citrus Live",
        venueCity: "Edinburg",
        venueState: "TX",
        imageName: "citrus-break-comedy-show.jpg",
        ticketUrl: "https://tixplug.com/shop/citrus-break-comedy-show/",
        isPublished: true
    },
    {
        artistName: "Panter Belico",
        eventName: "Live in Concert",
        eventDate: "2026-03-21T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-panter-belico.jpg",
        ticketUrl: "https://www.ticketmaster.com/panter-belico-hidalgo-texas-03-21-2026/event/3A006338AC3E4B8B",
        isPublished: true
    },
    {
        artistName: "Reik",
        eventName: "Tour 2026",
        eventDate: "2026-03-28T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-reik.jpg",
        ticketUrl: "https://www.ticketmaster.com/reik-tour-2026-hidalgo-texas-03-28-2026/event/3A006377F8B7D2C4",
        isPublished: true
    },
    {
        artistName: "Snow Tha Product",
        eventName: "BEFORE I CRASHOUT",
        eventDate: "2026-05-01T20:00:00",
        venueName: "HAPO Center",
        venueCity: "Pasco",
        venueState: "WA",
        imageName: "snow-tha-product-before-i-crashout.jpg",
        ticketUrl: "https://tixplug.com/shop/snow-tha-product-before-i-crashout/",
        isPublished: true
    },
    {
        artistName: "Emerson, Lake & Palmer",
        eventName: "The United Tour",
        eventDate: "2026-05-01T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-emerson-lake-palmer.jpg",
        ticketUrl: "https://www.ticketmaster.com/an-evening-with-emerson-lake-palmer-hidalgo-texas-05-01-2026/event/3A006364BE3AA8B1",
        isPublished: true
    },
    {
        artistName: "Alejandro Sanz",
        eventName: "Y Ahora Que Gira",
        eventDate: "2026-05-09T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-alejandro-sanz.jpg",
        ticketUrl: "https://www.ticketmaster.com/alejandro-sanz-y-ahora-que-gira-hidalgo-texas-05-09-2026/event/3A006355DAD69751",
        isPublished: true
    },
    {
        artistName: "Tacos, Tequilas & Chelas",
        eventName: "",
        eventDate: "2026-05-16T20:00:00",
        venueName: "Benton County Fairgrounds",
        venueCity: "",
        venueState: "TX",
        imageName: "tacos-tequilas-chelas.jpg",
        ticketUrl: "https://tixplug.com/shop/tacos-tequilas-chelas/",
        isPublished: true
    },
    {
        artistName: "Carin León",
        eventName: "De Sonora Para El Mundo Tour",
        eventDate: "2026-05-20T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-carin-le-n.jpg",
        ticketUrl: "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-20-2026/event/3A0064309908954C",
        dates: [
            { eventDate: "2026-05-20T20:00:00", ticketUrl: "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-20-2026/event/3A0064309908954C" },
            { eventDate: "2026-05-21T20:00:00", ticketUrl: "https://www.ticketmaster.com/carin-leon-de-sonora-para-el-hidalgo-texas-05-21-2026/event/3A0064309910955E" }
        ],
        isPublished: true
    },
    {
        artistName: "Puppy Pals Live",
        eventName: "Live Show",
        eventDate: "2026-05-28T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-puppy-pals-live.jpg",
        ticketUrl: "https://www.ticketmaster.com/puppy-pals-live-hidalgo-texas-05-28-2026/event/3A00644BF7033190",
        isPublished: true
    },
    {
        artistName: "Grupo Bryndis, Industria Del Amor & Guardianes",
        eventName: "Romanticos Tour",
        eventDate: "2026-05-29T20:00:00",
        venueName: "Payne Arena",
        venueCity: "Hidalgo",
        venueState: "TX",
        imageName: "payne-grupo-bryndis-industria-del-amor-guardianes.jpg",
        ticketUrl: "https://www.ticketmaster.com/grupo-bryndis-industria-del-amor-guardianes-hidalgo-texas-05-29-2026/event/3A00638999886744",
        isPublished: true
    },
    {
        artistName: "Seltzer Island",
        eventName: "",
        eventDate: "2026-06-20T20:00:00",
        venueName: "Cameron County Amphitheater",
        venueCity: "",
        venueState: "TX",
        imageName: "seltzer-island.jpg",
        ticketUrl: "https://tixplug.com/shop/seltzer-island/",
        schedule: [
            { time: "3:00 PM", description: "Doors Open" }
        ],
        isPublished: true
    }
];

export const LOCAL_CLUBS = [
    {
        id: "club-1",
        name: "17th St. Entertainment District",
        type: "Nightlife Hub",
        city: "McAllen",
        image: "assets/nightlife-17th.png",
        description: "The heartbeat of McAllen nightlife. A strip of bars, clubs, and lounges.",
        features: ["Multiple Venues", "Live Music", "Late Night"],
        link: "https://exploremcallen.com",
        lat: 26.203,
        lng: -98.230
    },
    {
        id: "club-2",
        name: "Clayton's Beach Bar",
        type: "Beach Bar",
        city: "South Padre Island",
        image: "assets/claytons.png",
        description: "The biggest beach bar in Texas. Live concerts, drinks, and ocean views.",
        features: ["Beachfront", "Concerts", "Fireworks"],
        link: "https://claytonsbeachbar.com",
        lat: 26.128,
        lng: -97.166
    },
    {
        id: "club-3",
        name: "Suerte Bar & Grill",
        type: "Upscale Bar",
        city: "McAllen",
        image: "assets/suerte.png",
        description: "Modern cantina with premium cocktails and a high-energy atmosphere.",
        features: ["Cocktails", "VIP Tables", "DJ"],
        link: "#",
        lat: 26.204,
        lng: -98.231
    }
];

export const LOCAL_RESTAURANTS = [
    {
        id: "food-1",
        name: "SALT - New American Table",
        type: "Fine Dining",
        city: "McAllen",
        price: "$$$",
        image: "assets/salt-1.jpg",
        description: "Chef-driven cuisine focusing on fresh, local ingredients.",
        features: ["Farm-to-Table", "Craft Cocktails", "Date Night"],
        link: "https://saltnewamericantable.com",
        lat: 26.230,
        lng: -98.240
    },
    {
        id: "food-2",
        name: "Sea Ranch Restaurant",
        type: "Seafood",
        city: "South Padre Island",
        price: "$$$",
        image: "assets/SeaRanchRestaurant.jpg",
        description: "Premier waterfront dining featuring wild-caught gulf seafood.",
        features: ["Waterfront View", "Fresh Seafood", "Marina"],
        link: "http://searanchrestaurant.com",
        lat: 26.100,
        lng: -97.170
    },
    {
        id: "food-3",
        name: "Taco Palenque",
        type: "Casual Dining",
        city: "McAllen",
        price: "$",
        image: "assets/taco-palenque.png",
        description: "Authentic Mexican cuisine. Perfect for late-night cravings after the show.",
        features: ["Late Night", "Drive-thru", "Authentic Flavor"],
        link: "https://tacopalenque.com",
        lat: 26.200,
        lng: -98.230
    }
];

export const LOCAL_HOTELS = [
    {
        id: "hotel-1",
        name: "Embassy Suites Convention Center",
        city: "McAllen",
        stars: 4,
        image: "assets/embassy-mcallen.png",
        description: "Located within walking distance of the McAllen Convention Center district.",
        features: ["Free Breakfast", "Pool", "Suites"],
        link: "https://www.hilton.com",
        lat: 26.195,
        lng: -98.257
    },
    {
        id: "hotel-2",
        name: "Isla Grand Beach Resort",
        city: "South Padre Island",
        stars: 4,
        image: "assets/isla-grand.png",
        description: "A beachfront resort offering a tropical escape with pools and dining.",
        features: ["Beachfront", "Resort Style", "Nightclub on-site"],
        link: "https://islagrand.com",
        lat: 26.090,
        lng: -97.160
    }
];
